repos:
  - repo: local
    hooks:
      - id: scan-secrets
        name: Scan secrets
        entry: make scan-secrets check=whole-history
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: check-file-format
        name: Check file format
        entry: make check-file-format check=all
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: check-markdown-format
        name: Check Markdown format
        entry: make check-markdown-format check=all
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: check-markdown-links
        name: Check Markdown links
        entry: make check-markdown-links check=all
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: check-shell-lint
        name: Check shell scripts
        entry: make check-shell-lint
        language: system
        pass_filenames: false
